# Generated by Django 5.2.7 on 2026-01-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='chromosome_location',
            field=models.CharField(help_text='Format: chr:start-end (e.g., chr17:41196312-41277500)', max_length=100, null=True, verbose_name='Lokalizacja w genomie'),
        ),
    ]
