# Generated by Django 5.2.7 on 2026-01-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_mutation_chromosome_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapycycle',
            name='protocol_name',
            field=models.CharField(max_length=200, verbose_name='Rodzaj terapii'),
        ),
    ]
