# Generated by Django 5.2.7 on 2026-01-31 19:36

import patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_therapycycle_protocol_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=patient.models.patient_directory_path),
        ),
    ]
