# Generated by Django 5.2.7 on 2026-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_medicaldocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Czy aktywny (Nieusunięty)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Czy aktywny (Nieusunięty)'),
        ),
    ]
