# Generated by Django 6.0.1 on 2026-02-01 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_medicaldocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='icd_code',
            field=models.CharField(blank=True, choices=[('C15', 'C15 - Nowotwór złośliwy przełyku'), ('C16', 'C16 - Nowotwór złośliwy żołądka'), ('C18', 'C18 - Nowotwór złośliwy jelita grubego'), ('C20', 'C20 - Nowotwór złośliwy odbytnicy'), ('C22', 'C22 - Nowotwór złośliwy wątroby'), ('C25', 'C25 - Nowotwór złośliwy trzustki'), ('C34', 'C34 - Nowotwór złośliwy oskrzela i płuca'), ('C43', 'C43 - Czerniak złośliwy skóry'), ('C50', 'C50 - Nowotwór złośliwy sutka (piersi)'), ('C53', 'C53 - Nowotwór złośliwy szyjki macicy'), ('C54', 'C54 - Nowotwór złośliwy trzonu macicy'), ('C56', 'C56 - Nowotwór złośliwy jajnika'), ('C61', 'C61 - Nowotwór złośliwy gruczołu krokowego'), ('C64', 'C64 - Nowotwór złośliwy nerki'), ('C67', 'C67 - Nowotwór złośliwy pęcherza moczowego'), ('C71', 'C71 - Nowotwór złośliwy mózgu'), ('C73', 'C73 - Nowotwór złośliwy tarczycy'), ('C81', 'C81 - Chłoniak Hodgkina'), ('C90', 'C90 - Szpiczak mnogi'), ('INNE', 'Inne rozpoznanie')], max_length=10, null=True, verbose_name='Kod ICD-10'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='metastasis_stage',
            field=models.CharField(blank=True, choices=[('M0', 'M0 - Brak przerzutów odległych'), ('M1', 'M1 - Obecne przerzuty odległe')], default='M0', max_length=10, null=True, verbose_name='Cecha M (Przerzuty)'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Rozpoznanie opisowe'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='node_stage',
            field=models.CharField(blank=True, choices=[('NX', 'NX - Nie można ocenić węzłów'), ('N0', 'N0 - Brak przerzutów do węzłów'), ('N1', 'N1 - Przerzuty do pojedynczych węzłów'), ('N2', 'N2 - Przerzuty do licznych węzłów'), ('N3', 'N3 - Rozległe przerzuty węzłowe')], default='NX', max_length=10, null=True, verbose_name='Cecha N (Węzły)'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patient.patient', verbose_name='Pacjent'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='tumor_stage',
            field=models.CharField(blank=True, choices=[('TX', 'TX - Nie można ocenić guza'), ('T0', 'T0 - Brak dowodów na obecność guza'), ('Tis', 'Tis - Rak przedinwazyjny (in situ)'), ('T1', 'T1 - Guz mały (I stopień)'), ('T2', 'T2 - Guz średni (II stopień)'), ('T3', 'T3 - Guz duży/nacieka (III stopień)'), ('T4', 'T4 - Guz bardzo duży/nacieka sąsiednie narządy')], default='TX', max_length=10, null=True, verbose_name='Cecha T (Guz)'),
        ),
    ]
