# Generated by Django 6.0.1 on 2026-02-01 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_alter_diagnosis_icd_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Odpowiedź na leczenie', 'verbose_name_plural': 'Odpowiedzi na leczenie'},
        ),
        migrations.AlterModelOptions(
            name='therapycycle',
            options={'verbose_name': 'Cykl terapii', 'verbose_name_plural': 'Cykle terapii'},
        ),
        migrations.RemoveField(
            model_name='therapycycle',
            name='protocol_name',
        ),
        migrations.AddField(
            model_name='therapycycle',
            name='scheme_name',
            field=models.CharField(default='Ogólny', max_length=100, verbose_name='Nazwa schematu (np. AC, Taxol)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapycycle',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapy_cycles', to='patient.diagnosis', verbose_name='Leczona choroba (z diagnoz pacjenta)'),
        ),
        migrations.AlterField(
            model_name='therapycycle',
            name='status',
            field=models.CharField(choices=[('W trakcie', 'W trakcie'), ('Zakończona', 'Zakończona'), ('Wstrzymana', 'Wstrzymana'), ('Zaplanowana', 'Zaplanowana')], default='Zaplanowana', max_length=20, verbose_name='Status terapii'),
        ),
    ]
