# Generated by Django 6.0.1 on 2026-02-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_alter_response_options_alter_therapycycle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mutation',
            options={},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='mutation',
            name='chromosome_location',
        ),
        migrations.RemoveField(
            model_name='mutation',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='mutation',
            name='vaf',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(default='2026-02-02 00:30', verbose_name='Data i godzina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='purpose',
            field=models.CharField(default='2026-02-02 00:30', max_length=200, verbose_name='Cel wizyty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutation',
            name='gene_name',
            field=models.CharField(default='2026-02-02 00:30', max_length=50, verbose_name='Nazwa genu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatkowe informacje'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='result',
            field=models.CharField(choices=[('Pozytywny', 'Pozytywny'), ('Negatywny', 'Negatywny'), ('Niejednoznaczny', 'Niejednoznaczny')], default='2026-02-02 00:30', max_length=20, verbose_name='Wynik'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutation',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data badania'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notatki'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Zaplanowana', 'Zaplanowana'), ('Odbyta', 'Odbyta'), ('Odwołana', 'Odwołana')], default='Zaplanowana', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mutation_type',
            field=models.CharField(max_length=100, verbose_name='Rodzaj mutacji'),
        ),
    ]
